### ISSUE TITLE
eslint prettier auto save invalid

### ISSUE THREAD

**Issue by wakaka378** [vuejs/create-eslint-config#9]
After using VUE3 to create a project, I found that it automatically saved the repair and failed

![image](https://github.com/vuejs/create-eslint-config/assets/46524158/8b941bfa-cfd6-4461-95c9-db0ca9f753bc)

I hope it is like this

![image](https://github.com/vuejs/create-eslint-config/assets/46524158/a9c21aba-0688-433e-be6f-e0cd052a8124)

I later discovered it
```
// eslint.json
{
  extends: [
    'plugin:vue/vue3-essential',
    'eslint:recommended',
    '@vue/eslint-config-typescript',
    '@vue/eslint-config-prettier/skip-formatting'
  ],
}

```

`'@vue/eslint-config-prettier/skip-formatting' `config why add 'skip-formatting'??

I turned it into
```
// eslint.json
{
  extends: [
   ...
    '@vue/eslint-config-prettier'
  ],
}

```
It started working

It is turned off in node_modules page

```js
// node_modules/@vue/eslint-config-prettier/skip-formatting.js
  rules: {
    "prettier/prettier": "off",
  },
```
So why use [eslintConfig.extends.push('@vue/eslint-config-prettier/skip-formatting')](https://github.com/vuejs/create-eslint-config/blob/b68a1c1217e3bed48cb0dbc7fe2e4517a2874c90/index.js#LL117C2-L117C2)configuration in the code

**Comment by sodatea** [comment]
Explained here: https://github.com/vuejs/eslint-config-prettier#use-separate-commands-for-linting-and-formatting

If you use Prettier alongside ESLint, I'd recommend only using Prettier to format your code.
